---
title: "MCMC Introduction"
output: html_document
---

# 概要

サンプリング手法から, MCMC法まで実装例を加えながらまとめる.

## モンテカルロ法 (Monte Carlo Method)

乱数を用いた数値積分法をモンテカルロ法と呼ぶ, モンテカルロ法の基礎は大数の強法則である. 

### モンテカルロ法

- 大数の弱法則

$\{X_n\}_{n=1}^\infty$を独立で, 分布が全て同じ確率変数の列とする. $E(X_i) = \mu, V(X_i) = \sigma^2 < \infty$ならば, 

$$S_n = X_1 + \dots + X_n$$

とおくとき, 任意の$\varepsilon > 0$に対して,

$$ \lim_{n \to \infty} P \left( \left| \frac{1}{n} S_n - \mu \right| < \varepsilon \right) = 0$$

- 大数の強法則

$\{X_n\}_{n=1}^\infty$を独立で, 分布が全て同じ確率変数の列とする. $E(X_i) = \mu$であり, 

$$\sum_{n=1}^\infty \frac{Var\{X_n\}}{n^2} < \infty$$

が成立すれば, 以下の大数の強法則が成立する.

$$\frac{S_n}{n} = \frac{X_1 + \dots + X_n}{n} \rightarrow \mu \quad (n \rightarrow \infty)$$

- 中心極限定理

$\{X_n\}_{n=1}^\infty$を独立で, 分布が全て同じ確率変数の列とする. $E(X_i) = \mu, V(X_i) = \sigma^2 < \infty$ならば,

$$\lim_{n \to \infty} P(\sqrt n (S_n / n - \mu) \leq z = \Phi(z/\sigma)$$

ここで$\Phi(\cdot)$は標準正規分布の累積分布関数である.

- モンテカルロ法

$X_1,X_2,\cdots$を密度関数$f(x)$に従う, 独立な確率変数列, $g(x)$を任意関数とする. $g(X_1), g(X_2), \cdots$も独立列であり, その平均は積分

$$E\{g(X_i)\} = \int g(x)f(x)dx$$

となる. 従ってもし$g(X_i)$の分散$\sigma_g^2$が存在すれば, 大数の強法則から確率1で

$$\frac{1}{n}\sum_{i=1}^n g(X_i) \rightarrow \int g(x)f(x)dx$$

となる. つまり十分に大きな$n$に対しては, 上記の左辺の標本平均は右辺の積分の近似値となる. これがモンテカルロ法の原理である.

### 重点サンプリング(Importance Sampling)法

### 重点サンプリングからの再サンプリング(SIR: Sampling Importance Resampling)法

### ブートストラップ(bootstrap)法

## マルコフ連鎖モンテカルロ法 (MCMC: Markov Chain Monte Carlo Methods)

MCMC法とはマルコフ連鎖を用いて, 高次元乱数を漸近的に発生させる手法の総称である. 一般空間(離散もしくは連続)空間$\mathcal X$上の密度関数$f(x), x=(x_1, \cdots, x_n) \in \mathcal X^n$に従うベクトル乱数$R=(r_1, \cdots, r_n)$を発生したい場合, $n$が非常に大きく, また$f(x)$が複雑な場合, $R$を直接発生することは一般的に困難か不可能となる. さらに典型的な場合$f(x)$は

$$f(x) = \frac{1}{Z}g(x), \quad Z = \int_{\mathcal X^n} g(x)dx$$

の形をもち, $g(x)$は比較的簡単に計算できるが, 高次元積分(もしくは多重和)である正規化定数$Z$が理論的にも数値的にも計算できないという状況が対象である.

### 有限状態空間上のマルコフ連鎖

有限状態空間$S=\{1,\cdots,N\}$上のマルコフ連鎖$X=\{X_0,X_1,\cdots\}$が定常推移行列

$$P = (p_{ij}), \quad p_{ij} = P\{X_{t+1} = j | X_t = i\}, \quad i,j \in S, \quad t = 0,1,\cdots$$

を持つとすると, $P$の各行の総和は1となる. $P$の行列としての$n$乗を$P^n = (p_{ij}^n)$と置くと,

# 参考文献

1. Gelman, A. (2013). *Bayesian Data Analysis, Third Edition*. Chapman and Hall/CRC. 
1. 間瀬 茂. (2016) 「ベイズ法の基礎と応用」日本評論社.

